### PR TITLE
Fix AIT*'s clear method

### PR DESCRIPTION
**Pull request by marlinstrub**
The k-nearest RGG constant should not be reset because it is not computed when AIT* solves a problem. Sorry, this was a silly mistake.

### CODE REVIEW

**Comment by mamoll** [comment]
@marlinstrub unit tests are still failing in CI: https://travis-ci.org/github/ompl/ompl

**Comment by gammell** [comment]
Hi Mark,

Does the CI run any different tests on the master than it does on a PR? The PR had passed all it's tests, so why would it fail now unless something was different or the failure was a result of the random seed?

I'm also not sure that this one has anything to do with AIT*?
https://travis-ci.org/github/ompl/ompl/jobs/693164529#L448

I'm sure Marlin will look into the other,
Jon

**Comment by mamoll** [comment]
Retriggering the build fixed the bionic/gcc build. The macOS build is still failing. I can reproduce it on my machine. I get errors like these:
```
Testing AITstar ...
/Users/mmoll/omplapp/ompl/tests/geometric/2d/2dcircles_optimize.cpp:169: error: in "MyPlanTestFixture/geometric_AITstar": check pdef->hasOptimizedSolution() || opt->isCostEquivalentTo(ini_cost, prev_cost) has failed
/Users/mmoll/omplapp/ompl/tests/geometric/2d/2dcircles_optimize.cpp:173: error: in "MyPlanTestFixture/geometric_AITstar": check !opt->isCostBetterThan(prev_cost, min_cost) has failed
Done with AITstar.
```
The weird thing is that if I run `./bin/test_2dcircles_opt_geometric` directly from the build directory, then the errors disappear. I am not sure why running `ctest -j1` would fail. Even weirder, `ctest --tests-regex test_2dcircles_opt_geometric` **succeeds**!

**Comment by mamoll** [comment]
Maybe you can run `valgrind` to make sure there aren't any weird memory corruption errors. It's possible that the corruption is happening on Linux, too, but you just happen to get lucky there.

**Comment by gammell** [comment]
I think Marlin's got a bead on it. He said he had some commitments tonight (European time) before he was able to finish the solution.

I'll allow him to explain when he's got it sorted, but the way I understood it was that it looks like an interplay of the test design with the properties of AIT*.

**Comment by mamoll** [comment]
Thanks. I ran `valgrind` on Linux, and as I expected there are definitely some issues:
```
==12305== 
==12305== HEAP SUMMARY:
==12305==     in use at exit: 1,795,483 bytes in 11,306 blocks
==12305==   total heap usage: 30,960,944 allocs, 30,949,638 frees, 3,761,254,432 bytes allocated
==12305== 
==12305== 61,632 (16 direct, 61,616 indirect) bytes in 1 blocks are definitely lost in loss record 170 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BBF0F: allocate (new_allocator.h:111)
==12305==    by 0x51BBF0F: allocate (alloc_traits.h:436)
==12305==    by 0x51BBF0F: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BBF0F: void std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > >::_M_realloc_insert<std::shared_ptr<ompl::geometric::aitstar::Vertex> const&>(__gnu_cxx::__normal_iterator<std::weak_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > > >, std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (vector.tcc:406)
==12305==    by 0x51DA9AF: ompl::geometric::AITstar::performForwardSearchIteration() (AITstar.cpp:801)
==12305==    by 0x51DBC34: ompl::geometric::AITstar::iterate() (AITstar.cpp:640)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x11684A: ompl::base::PlannerTest::testSolveAndClear() (PlannerTest.h:72)
==12305==    by 0x1182A4: test (PlannerTest.h:96)
==12305==    by 0x1182A4: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:112)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305==    by 0x112C3B: MyPlanTestFixture::geometric_AITstar_invoker() (2dcircles_optimize.cpp:419)
==12305==    by 0x5B712CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305==    by 0x5B7077C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305== 
==12305== 71,624 (304 direct, 71,320 indirect) bytes in 1 blocks are definitely lost in loss record 172 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BBA46: allocate (new_allocator.h:111)
==12305==    by 0x51BBA46: allocate (alloc_traits.h:436)
==12305==    by 0x51BBA46: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BBA46: _M_allocate_and_copy<__gnu_cxx::__normal_iterator<const std::shared_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > > (stl_vector.h:1260)
==12305==    by 0x51BBA46: std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > >::operator=(std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > const&) (vector.tcc:206)
==12305==    by 0x51B7E9C: ompl::geometric::aitstar::Vertex::cacheNeighbors(std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > const&) const (Vertex.cpp:368)
==12305==    by 0x51AC375: ompl::geometric::aitstar::ImplicitGraph::getNeighbors(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) const (ImplicitGraph.cpp:392)
==12305==    by 0x51D8C38: ompl::geometric::AITstar::reverseSearchUpdateVertex(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (AITstar.cpp:993)
==12305==    by 0x51DB11F: ompl::geometric::AITstar::performReverseSearchIteration() (AITstar.cpp:952)
==12305==    by 0x51DB9FC: ompl::geometric::AITstar::iterate() (AITstar.cpp:570)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x50E9B15: ompl::base::Planner::solve(double) (Planner.cpp:143)
==12305==    by 0x116AC1: ompl::base::PlannerTest::testSolveAndClear() (PlannerTest.h:83)
==12305==    by 0x1182A4: test (PlannerTest.h:96)
==12305==    by 0x1182A4: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:112)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305== 
==12305== 71,728 (128 direct, 71,600 indirect) bytes in 1 blocks are definitely lost in loss record 173 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BCB64: allocate (new_allocator.h:111)
==12305==    by 0x51BCB64: allocate (alloc_traits.h:436)
==12305==    by 0x51BCB64: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BCB64: void std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > >::_M_realloc_insert<std::weak_ptr<ompl::geometric::aitstar::Vertex> >(__gnu_cxx::__normal_iterator<std::weak_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > > >, std::weak_ptr<ompl::geometric::aitstar::Vertex>&&) (vector.tcc:406)
==12305==    by 0x51BB6EA: emplace_back<std::weak_ptr<ompl::geometric::aitstar::Vertex> > (vector.tcc:105)
==12305==    by 0x51BB6EA: push_back (stl_vector.h:954)
==12305==    by 0x51BB6EA: ompl::geometric::aitstar::Vertex::addToReverseChildren(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (Vertex.cpp:305)
==12305==    by 0x51D972B: ompl::geometric::AITstar::reverseSearchUpdateVertex(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (AITstar.cpp:1137)
==12305==    by 0x51DB11F: ompl::geometric::AITstar::performReverseSearchIteration() (AITstar.cpp:952)
==12305==    by 0x51DB9FC: ompl::geometric::AITstar::iterate() (AITstar.cpp:570)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x1166FD: ompl::base::PlannerTest::testSolveAndClear() (PlannerTest.h:67)
==12305==    by 0x1182A4: test (PlannerTest.h:96)
==12305==    by 0x1182A4: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:112)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305==    by 0x112C3B: MyPlanTestFixture::geometric_AITstar_invoker() (2dcircles_optimize.cpp:419)
==12305== 
==12305== 160,000 (128 direct, 159,872 indirect) bytes in 1 blocks are definitely lost in loss record 174 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BCB64: allocate (new_allocator.h:111)
==12305==    by 0x51BCB64: allocate (alloc_traits.h:436)
==12305==    by 0x51BCB64: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BCB64: void std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > >::_M_realloc_insert<std::weak_ptr<ompl::geometric::aitstar::Vertex> >(__gnu_cxx::__normal_iterator<std::weak_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > > >, std::weak_ptr<ompl::geometric::aitstar::Vertex>&&) (vector.tcc:406)
==12305==    by 0x51BB6EA: emplace_back<std::weak_ptr<ompl::geometric::aitstar::Vertex> > (vector.tcc:105)
==12305==    by 0x51BB6EA: push_back (stl_vector.h:954)
==12305==    by 0x51BB6EA: ompl::geometric::aitstar::Vertex::addToReverseChildren(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (Vertex.cpp:305)
==12305==    by 0x51D972B: ompl::geometric::AITstar::reverseSearchUpdateVertex(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (AITstar.cpp:1137)
==12305==    by 0x51DB11F: ompl::geometric::AITstar::performReverseSearchIteration() (AITstar.cpp:952)
==12305==    by 0x51DB9FC: ompl::geometric::AITstar::iterate() (AITstar.cpp:570)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x50E9A61: ompl::base::Planner::solve(double) (Planner.cpp:144)
==12305==    by 0x1183AF: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:131)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305==    by 0x112C3B: MyPlanTestFixture::geometric_AITstar_invoker() (2dcircles_optimize.cpp:419)
==12305== 
==12305== 234,632 (672 direct, 233,960 indirect) bytes in 2 blocks are definitely lost in loss record 177 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BBA46: allocate (new_allocator.h:111)
==12305==    by 0x51BBA46: allocate (alloc_traits.h:436)
==12305==    by 0x51BBA46: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BBA46: _M_allocate_and_copy<__gnu_cxx::__normal_iterator<const std::shared_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > > (stl_vector.h:1260)
==12305==    by 0x51BBA46: std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > >::operator=(std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > const&) (vector.tcc:206)
==12305==    by 0x51B7E9C: ompl::geometric::aitstar::Vertex::cacheNeighbors(std::vector<std::shared_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::shared_ptr<ompl::geometric::aitstar::Vertex> > > const&) const (Vertex.cpp:368)
==12305==    by 0x51AC375: ompl::geometric::aitstar::ImplicitGraph::getNeighbors(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) const (ImplicitGraph.cpp:392)
==12305==    by 0x51D8C38: ompl::geometric::AITstar::reverseSearchUpdateVertex(std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (AITstar.cpp:993)
==12305==    by 0x51DB11F: ompl::geometric::AITstar::performReverseSearchIteration() (AITstar.cpp:952)
==12305==    by 0x51DB9FC: ompl::geometric::AITstar::iterate() (AITstar.cpp:570)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x50E9B15: ompl::base::Planner::solve(double) (Planner.cpp:143)
==12305==    by 0x1184C6: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:145)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305== 
==12305== 338,984 (16 direct, 338,968 indirect) bytes in 1 blocks are definitely lost in loss record 179 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51BBF0F: allocate (new_allocator.h:111)
==12305==    by 0x51BBF0F: allocate (alloc_traits.h:436)
==12305==    by 0x51BBF0F: _M_allocate (stl_vector.h:172)
==12305==    by 0x51BBF0F: void std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > >::_M_realloc_insert<std::shared_ptr<ompl::geometric::aitstar::Vertex> const&>(__gnu_cxx::__normal_iterator<std::weak_ptr<ompl::geometric::aitstar::Vertex>*, std::vector<std::weak_ptr<ompl::geometric::aitstar::Vertex>, std::allocator<std::weak_ptr<ompl::geometric::aitstar::Vertex> > > >, std::shared_ptr<ompl::geometric::aitstar::Vertex> const&) (vector.tcc:406)
==12305==    by 0x51DA9AF: ompl::geometric::AITstar::performForwardSearchIteration() (AITstar.cpp:801)
==12305==    by 0x51DBC34: ompl::geometric::AITstar::iterate() (AITstar.cpp:640)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x50E9A61: ompl::base::Planner::solve(double) (Planner.cpp:144)
==12305==    by 0x1183AF: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:131)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305==    by 0x112C3B: MyPlanTestFixture::geometric_AITstar_invoker() (2dcircles_optimize.cpp:419)
==12305==    by 0x5B712CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305==    by 0x5B7077C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305== 
==12305== 856,883 (392 direct, 856,491 indirect) bytes in 1 blocks are definitely lost in loss record 181 of 181
==12305==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12305==    by 0x51ABF1F: allocate (new_allocator.h:111)
==12305==    by 0x51ABF1F: allocate (alloc_traits.h:436)
==12305==    by 0x51ABF1F: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<ompl::geometric::aitstar::Vertex, std::allocator<ompl::geometric::aitstar::Vertex>, (__gnu_cxx::_Lock_policy)2> > > (allocated_ptr.h:104)
==12305==    by 0x51ABF1F: __shared_count<ompl::geometric::aitstar::Vertex, std::allocator<ompl::geometric::aitstar::Vertex>, std::shared_ptr<ompl::base::SpaceInformation>&, std::shared_ptr<ompl::base::ProblemDefinition>&, long unsigned int&> (shared_ptr_base.h:635)
==12305==    by 0x51ABF1F: __shared_ptr<std::allocator<ompl::geometric::aitstar::Vertex>, std::shared_ptr<ompl::base::SpaceInformation>&, std::shared_ptr<ompl::base::ProblemDefinition>&, long unsigned int&> (shared_ptr_base.h:1295)
==12305==    by 0x51ABF1F: shared_ptr<std::allocator<ompl::geometric::aitstar::Vertex>, std::shared_ptr<ompl::base::SpaceInformation>&, std::shared_ptr<ompl::base::ProblemDefinition>&, long unsigned int&> (shared_ptr.h:344)
==12305==    by 0x51ABF1F: allocate_shared<ompl::geometric::aitstar::Vertex, std::allocator<ompl::geometric::aitstar::Vertex>, std::shared_ptr<ompl::base::SpaceInformation>&, std::shared_ptr<ompl::base::ProblemDefinition>&, long unsigned int&> (shared_ptr.h:691)
==12305==    by 0x51ABF1F: make_shared<ompl::geometric::aitstar::Vertex, std::shared_ptr<ompl::base::SpaceInformation>&, std::shared_ptr<ompl::base::ProblemDefinition>&, long unsigned int&> (shared_ptr.h:707)
==12305==    by 0x51ABF1F: ompl::geometric::aitstar::ImplicitGraph::addSamples(unsigned long) (ImplicitGraph.cpp:328)
==12305==    by 0x51DB8F9: ompl::geometric::AITstar::iterate() (AITstar.cpp:681)
==12305==    by 0x51DBE30: ompl::geometric::AITstar::solve(ompl::base::PlannerTerminationCondition const&) (AITstar.cpp:232)
==12305==    by 0x50E9B15: ompl::base::Planner::solve(double) (Planner.cpp:143)
==12305==    by 0x1184C6: TestPlanner::test2DCirclesGeneral(Circles2D const&, std::shared_ptr<ompl::base::SpaceInformation> const&, double) (2dcircles_optimize.cpp:145)
==12305==    by 0x119836: TestPlanner::test2DCircles(Circles2D const&) (2dcircles_optimize.cpp:78)
==12305==    by 0x112960: run2DCirclesTest (2dcircles_optimize.cpp:380)
==12305==    by 0x112960: runAllTests<AITstarTest> (2dcircles_optimize.cpp:387)
==12305==    by 0x112960: MyPlanTestFixture::geometric_AITstar::test_method() (2dcircles_optimize.cpp:419)
==12305==    by 0x112C3B: MyPlanTestFixture::geometric_AITstar_invoker() (2dcircles_optimize.cpp:419)
==12305==    by 0x5B712CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305==    by 0x5B7077C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305==    by 0x5B70860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==12305== 
==12305== LEAK SUMMARY:
==12305==    definitely lost: 1,656 bytes in 8 blocks
==12305==    indirectly lost: 1,793,827 bytes in 11,298 blocks
==12305==      possibly lost: 0 bytes in 0 blocks
==12305==    still reachable: 0 bytes in 0 blocks
==12305==         suppressed: 0 bytes in 0 blocks
==12305== 
==12305== For counts of detected and suppressed errors, rerun with: -v
==12305== ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
```

**Comment by gammell** [comment]
Hm, those are worrying but they're all about memory being lost, so they shouldn't result in nondeterministic behaviour, just memory leaks. I think?

We will have to look at them closer, but I briefly looked at the first one and it's occurring on a construction of a `weak_ptr` from a `shared_ptr`. At the moment, I can't think of any reason within the control of the end-user that would cause a memory leak... I'm sure there is one though.

**Comment by gammell** [comment]
I ran #724 through `valgrind` on my machine (Ubuntu 18.04) and got no errors.

**Comment by marlinstrub** [comment]
> ```
> Testing AITstar ...
> /Users/mmoll/omplapp/ompl/tests/geometric/2d/2dcircles_optimize.cpp:169: error: in "MyPlanTestFixture/geometric_AITstar": check pdef->hasOptimizedSolution() || opt->isCostEquivalentTo(ini_cost, prev_cost) has failed
> /Users/mmoll/omplapp/ompl/tests/geometric/2d/2dcircles_optimize.cpp:173: error: in "MyPlanTestFixture/geometric_AITstar": check !opt->isCostBetterThan(prev_cost, min_cost) has failed
> Done with AITstar.
> ```

As far as I can tell #724 fixes these issues (I updated the PR comment to clarify how). For what it's worth, they didn't show up on my machine when testing with #723. On my machine valgrind also doesn't report any errors or leaks (with #724) but given that my machine is similar to Jon's that's not a big surprise. Please let me know if you encounter any further issues with AIT*.

**Pull request merged**
