### PR TITLE
Informed sampling multistart/goal support, BIT* MoveIt! and infinite problem support

### PR DESCRIPTION
**Pull request by gammell**
This is the last PR I had in my queue. It's a couple things.

1. Support for multiple starts/goals in `PathLengthDirectInfSampler`,
2. Support for the MoveIt! workflow in `BIT*`,
3. Support for planning problems with infinite bounds in `BIT*`,
4. A couple other new ideas for `BIT*`, and
5. Documentation updates for `PathLengthDirectInfSampler,` `InformedRRT*` and `BIT*` to support the upcoming release.

Will rebase when it's ready to go.

### CODE REVIEW

**Comment by mamoll** [comment]
Overall, looks good. Looks most (all?) changes only affect BIT*. Is that right? I am not a fan of std::list, and would use std::vector for the start and goal states, but performance is likely not a huge deal here.

**Comment by gammell** [comment]
All the changes are to informed code, specifically either to `PathLengthDirectInfSampler` or `BIT*`.

All the other changes in files are just little documentation/consistency things, like making sure that both the direct and rejection-based informed samplers use the `virtual` keyword in the functions they overload.

Should I rebase?

**Comment by mamoll** [comment]
Yes, please (if it's not too much trouble).

**Comment by gammell** [comment]
Not at all, I'm getting better at it through trial and error. :wink:

**Comment by gammell** [comment]
Mark,
Thanks again for all the guidance and help with integrating my code.

I actually just realised I have a small bug fix for the infinite-problem case. I'll create a PR for that once I finish testing it in an hour or so, but don't worry, this isn't the start of a thousand little PRs. :smile:

**Pull request merged**
