### PR TITLE
Hook for adding start and goal state with non-scoped state

### PR DESCRIPTION
**Pull request by davetcoleman**

### CODE REVIEW

**Comment by davetcoleman** [comment]
Talked with @mamoll on phone, we decided against adding this

**Comment by davetcoleman** [comment]
@mamoll do you recall the reason we decided against adding this? i'd actually like to still have it merged it as i keep having to use this patch

**Comment by mamoll** [comment]
I think the idea was that SimpleSetup provides a high-level interface to the lower level OMPL functionality. We should discourage people from using raw pointers in a high-level API.

**Comment by zkingston** [comment]
I agree with the point that SimpleSetup should discourage use of raw pointers, particularly for states where it can be tricky to do memory management right. Closing this pull unless there is interest in keeping it alive.

**Pull request closed without merging**
