### PR TITLE
Bitstar cleanup and fixes

### PR DESCRIPTION
**Pull request by gammell**
Fixes:

- Removal of unused variable warning in RRT#
- Missed fix re: Bitbucket issue #364
- Bitbucket issue #379

Improvements/cleanup:

- Use the OMPL binary heap datastructure
- Store queue pointers in vertices (instead of a convoluted map hashed by vertex ID)
- New debug asserts
- Misc. other cleanups

### CODE REVIEW

**Comment by gammell** [comment]
I'm still running a few final tests of these changes on my computer, but I wanted to create the PR so I could point Issue #379 at it.

**Comment by gammell** [comment]
I was going to say that I'm happy with my personal test and think it can be merged whenever you want but I see Travis CI disagrees, so I will take a look at that tomorrow.

**Comment by mamoll** [comment]
Travis CI is now also happy. Some of the unit tests are probabilistic in nature and will sometimes fail. Rerunning the job made all tests pass. This looks ready to merge. Thanks!

**Comment by gammell** [comment]
Great news, thanks.

**Pull request merged**
