### PR TITLE
BIT* updates and a new associated algorithm, SORRT*

### PR DESCRIPTION
**Pull request by gammell**
This is the big PR I was warning about. After two days of manual C++11 merges and rebasing to make sure everything was ok, I think it is finally ready.

I am not sure how it is affected by the possible refactoring of RRT*.

### CODE REVIEW

**Comment by gammell** [comment]
I had some thoughts over the weekend on ways to simplify the code a bit, so I'm going to add those into the PR. I'll leave this open and just ping again once I'm done cleaning things up.

**Comment by ArekSredzki** [comment]
@gammell +1, we're hoping to work off of BIT* at UBC Sailbot. Would you be available to finish preparing this for merge in the near future? Many thanks :)

**Comment by gammell** [comment]
@ArekSredzki, that looks like a really interesting project! Things took a turn for the busier the last couple months for me and I won't have time to do my hinted-at improvements until at least the end of Nov.; however, if @mamoll doesn't mind the extra PR, I could fix the merge conflicts here and do those improvements as a separate PR later.

Just FYI, as far as I know, there's nothing particularly wrong with the version of BIT* currently in OMPL (tho' this one is better in some edge cases). Alternatively, you can always clone this PR directly from its repo: https://github.com/utiasASRL/batch-informed-trees/tree/bitstar_update_pr

Let me know.
Jon

**Comment by mamoll** [comment]
I'd be happy to merge in principle, but the build is failing on Travis. Can you fix the errors first?

**Comment by gammell** [comment]
OK,
I'll try and get the build failure sorted out in a few days. Then we can just do a second PR when I find time to make further fixes.

**Comment by gammell** [comment]
Build errors all fixed.
They were linking issues relating to a templated function that didn't appear on my machine.
@mamoll, hopefully this can now be merged?

**Comment by ArekSredzki** [comment]
Thank you @gammell !

**Pull request merged**
