### PR TITLE
Add pybindings to ST-RRT* planner

### PR DESCRIPTION
**Pull request by aorthey**
This MR creates pybindings so that the ST-RRT* planner is usable using python. 

I also translated the cpp demo example to a py demo example.

### CODE REVIEW

**Comment by zkingston** [comment]
I currently get the following error in binding generation for the `base` module, probably due to the inclusion of the `StateTimeStateSpace`:
```
Traceback (most recent call last):
  File "/home/zak/src/ompl/py-bindings/generate_bindings.py", line 975, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/zak/src/ompl/py-bindings/generate_bindings.py", line 154, in __init__
    code_generator_t.__init__(self, 'base', ['bindings/util'], replacement)
  File "/home/zak/src/ompl/py-bindings/ompl/bindings_generator.py", line 156, in __init__
    self.mb.split_module('bindings/' + name, use_files_sum_repository=True)
  File "/home/zak/src/pyplusplus/pyplusplus/module_builder/boost_python_builder.py", line 385, in split_module
    written_files = file_writers.write_multiple_files(
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/__init__.py", line 37, in write_multiple_files
    mfs.write()
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/multiple_files.py", line 396, in write
    self.split_classes()
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/multiple_files.py", line 300, in split_classes
    for cls in class_creators: self.split_class(cls)
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/multiple_files.py", line 288, in split_class
    self.split_class_impl( class_creator )
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/multiple_files.py", line 260, in split_class_impl
    self.write_file( header_name
  File "/home/zak/src/pyplusplus/pyplusplus/file_writers/multiple_files.py", line 56, in write_file
    raise RuntimeError( os.linesep.join(msg) )
RuntimeError: `Py++` is going to write different content to the same file(bindings/base/type.pypp.hpp).
```

**Comment by zkingston** [comment]
Actually, it might be due to the `Motion` class brought in by the `ConditionalStateSampler`.

**Comment by aorthey** [comment]
Hm, weird. I also had some problems with the Py++ module. I got it to work by upgrading the package. For me (on Ubuntu 20.04) I used `python3.8 -m pip install pyplusplus --upgrade`. Maybe your issue is something similar, i.e. some pyplusplus version mismatch?

**Comment by zkingston** [comment]
@aorthey I rebased and fixed compilation of the bindings for me - there was an issue creating a name conflict that might be platform dependent (a vector of const states and vector of motions creating the same output Python file, causing Py++ to break on my side, the `const` can come either before or after and I bet it's a castxml/pygccxml issue).

**Review by zkingston — APPROVED** [review]

**Pull request merged**
