### PR TITLE
Optionally check for clearance with DiscreteMotionValidator

### PR DESCRIPTION
**Pull request by davetcoleman**
As described. I'm using this with the SPARS algorithm

### CODE REVIEW

**Comment by mamoll** [comment]
Why can't you just make the clearance check part of your state validity checker?

**Comment by davetcoleman** [comment]
I made this a few months ago, but I think the reason is because I actually have different clearance criteria for edges vs. vertices. Basically I want all vertices to be distance d from a nearest obstacle, but I have no clearance for edges. This reduces the size of the graph because it "softens" sharp edges in the invalid regions.

Reviewing the original SPARS journal paper though, it appears they enforced the same clearance for edges and vertices. Is what I'm proposing sound like an absurd idea to you?

**Comment by mamoll** [comment]
I'd set a valid state sampler instead that tries to pick samples with large clearance such as MinimumClearanceValidStateSampler (written by you!) or MaximizeClearanceValidStateSampler. That way you don't need to test for clearance on the edges.

**Comment by davetcoleman** [comment]
> That way you don't need to test for clearance on the edges.

I don't understand - you can sample two vertices with proper clearance but have their associated edge violate that same clearance.

**Comment by mamoll** [comment]
Yes, but you mentioned that in your particular case, you had said you didn't have any clearance requirements on the edges.

**Comment by davetcoleman** [comment]
That's true. I've been working on the smoother recently so this is now very fresh in my mind. I'm using a clearance amount on the DiscreteMotionValidator when using ``geometric/PathSimplifier`` *until the very last step* when I run ``reduceVertices()`` with no clearance. This, as it turns out, keeps all the vertices having a clearance but allows edges to violate the clearance. The result is that I have a very smooth path around obstacles with the minimum number of vertices.

**Comment by zkingston** [comment]
Following previous discussion, this could be implemented as a custom motion validator or validity checker. Closing unless there is further interest given age of the pull.

**Pull request closed without merging**
