### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by mosfet80**
flann changelogs:
Version 1.9.2
        * Removed redundant assignment (issue #422 @fluber)
        * Removed unnecessary null checks before delete (issue #420 @elfring)
        * Reverted PR #424 due to lack of portability
        * fscanf fix (PR #467 @rdelfin)
        * Out of bounds check (modified PR #455 @legrosbuffle, also included in PR #319 @seth-planet)
        * Fixed MacOS build (PR #470 @johnhe4, modified for linux)
	* Fixed build system with dummy.c hack (PR #457 @pemmanuelviel)
	* Fixed misleading indentation in util/any.h (PR #365 @psteinb, also PR #428, #430, #459)
	* Included datasets in repo
	* Correct typo in definition (PR #419 @SergioRAgostinho) * Fix typos (PR #279 @gadomski)
	* CMakefile CUDA sources fix (PR #458 @pemmanuelviel)
	* Documentation fix (PR #456 @pemmanuelviel)
	* Scoping issue fix (PR #405 @greenbrettmichael, also PR #469, issue #386)
	* Documentation fixes (PR #460 @pemmanuelviel)
	* Changed return value (PR #461 @pemmanuelviel)
	* Fixed CUDA crash - guarantee prealloc > 0 (PR #437 @neka-rat)
	* Fixed wrong variable use (PR #433 @XinyiYS)
	* Fixed RNG initialization (PR #424 @SiddhantRanade)
	* Updated link to PDF (PR #474 @kleinma)
Version 1.8.5
        *Allow flann to build with VS2015

### CODE REVIEW

**Comment by kleinma** [comment]
> * Updated link to PDF (PR [#474](https://github.com/ompl/ompl/issues/474) @kleinma)

I'm flattered by the mention! But, this wasn't me.

**Comment by mosfet80** [comment]
@kleinma I copied the flann library changelogs.

**Comment by zkingston** [comment]
Is this version upgrade needed? If you have a more modern FLANN installed OMPL should find and compile just fine.

**Comment by mosfet80** [comment]
@zkingston Sure, I have flan updated and it compiles perfectly.
However, users who need to download it should not use an old  version that has bugs.
I believe that some already reported problems can be automatically fixed with this update https://github.com/ompl/ompl/issues/1004

**Comment by zkingston** [comment]
Yes, but out-of-the-box repository installations on Ubuntu 20/22 (=1.9.1) would be unable to use FLANN. OMPL supports other legacy installations as well, such as Ubuntu 16/18. The linked issue does not mention FLANN anywhere. If OMPL begins to leverage modern features of FLANN that require a version update or FLANN changes its API between versions I am open to bumping the version, but not simply to match the current latest release.

**Pull request closed without merging**
