### PR TITLE
Fix vector subscript out of range

### PR DESCRIPTION
**Pull request by davetcoleman**
Ig Manu reported:

> I'm trying to implement a path planning
> algorithm, but with the Thunder framework I keep getting an error, when
> doPostProcessing() is called (everything before works fine)
> 
> Vector Subscript is out of Range. In Sparsedb.cpp line 815:
> i == addedStateIDs[usedIDTracker]
> 
> Do you have an idea, what could cause this? I'm building on Visual Studio 2015.

This PR changes one line to have an extra check for this error.

Also small variable name formatting fix included.

### CODE REVIEW

**Comment by kapsl** [comment]
Hi Dave,
and thanks for your reply! I will test the changes on Monday - and report the outcome. Lightning Framework works without problems...

I found an additional problem, related to Boost and the Thunder Framework. We have linked ompl into an C# .NET Application with \CLR and till now, everything works perfect. But in the depth_first_search.hpp there's a problem with \CLR. 

See here: https://stackoverflow.com/questions/33391901/c2664-error-with-boost-depth-first-search-hpp-when-compiling-with-clr
and here
https://github.com/CGAL/cgal/issues/435

**Comment by davetcoleman** [comment]
that sounds like a boost + .NET issue - is it Thunder specific? I don't do windows :)

**Comment by kapsl** [comment]
Hi, 
I tested it on native cpp and the bugfixes seem to work! Great, thank you! I will write if i found a solution to the compiler problem with boost & clr. It is a boost problem, but it's as far as I discovered till now, the only file in ompl that doesn't compile on windows with clr...

**Comment by kapsl** [comment]
I did now find a workaround for the boost \clr problem: In depth_first_search.hpp do following:

When commenting out the line BOOST_TTI_HAS_MEMBER_FUNCTION(finish_edge) and replacing the line do_call_finish_edge

it works for me...

**Comment by kapsl** [comment]
Ok i found a new problem. Sorry ;-) 
When i now saved the thunder.db and try to restart it again. It shows output as you can see in the image. At this point it hangs - no error just nothing happens afterwards...

thunder

**Comment by kapsl** [comment]
Ok i think i found the problem - my boost-hack was it. In line 81 on depth_first_search I commented out the do_call_finish_edge line completely. So this function now doesn't do anything at the moment. But it seems to work?!

**Comment by davetcoleman** [comment]
I wonder if this recent PR affects windows compatibility: https://github.com/ompl/ompl/pull/72

Perhaps revert that commit in your source code and see if it compiles with Windows?

**Pull request merged**
