### PR TITLE
Miscellanea - Local seeds for RNG

### PR DESCRIPTION
**Pull request by gammell**
Third try's hopefully the charm. Just local seeds for RNGs, no tunnelling them through StateSamplers. As discussed in prior pull request (#42).

These are clean-up changes before pull pull requests for Informed RRT* and BIT*.

### CODE REVIEW

**Comment by isucan** [comment]
Looks great! No comments for the code. Thank you for your contribution! Perhaps we could collapse these commits into one?

**Comment by gammell** [comment]
Sure. I must confess I'm not very experienced with git/github, so is this what you had in mind?
  https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
It looks like I will need to undo this PR and create a new branch to do so?

Jon

**Comment by mamoll** [comment]
Looks good to me, too. If collapsing commits is tricky, you can also send me a patch and I'll commit on your behalf (with your user name).

**Comment by gammell** [comment]
To be honest, I don't mind making a "pull request" branch. It will probably make it easier to parcel future requests into logical chunks... And I definitely don't mind losing the commit history, it's a mess anyways.

I'll close this and squash the commits into a new branch... so 4th try it is. ;)

**Pull request closed without merging**
