### PR TITLE
Moved ANSI colors to header files

### PR DESCRIPTION
**Pull request by davetcoleman**
So that the colors can be used elsewhere

### CODE REVIEW

**Comment by mamoll** [comment]
Do the includes need to be moved as well? That seems unnecessary (and will slow down compilation a bit).

**Comment by isucan** [comment]
+1 for keeping includes where they are. This exposes us to using colors for situations where they do not work.... but maybe that's ok since it is just slightly broken output generated by non-OMPL macros?

**Comment by davetcoleman** [comment]
Ah, I didn't think about the includes - I guess they can stay where they were. I'm not actually sure exactly what they do but I thought they were required with the color defines.

**Comment by mamoll** [comment]
The includes are needed for istty and fileno. I noticed that you use the colors in the Thunder pull request (and don't use istty). Three questions:
- Do you want to way in the output handler to force color, even if output is redirected to a file? In that case, the colors would still show up correctly if you look at the file in a terminal (maybe, I haven't tried).
- Would it be possible to limit your custom color output messages to use colors that aren't already in use by the standard OMPL log commands?
- Furthermore, would it be possible to limit these message to verbose mode (and have verbose=false by default)?

I know I am rather particular about this, but I feel strongly that (a) colors should be used consistently, and (b) diagnostic info for developers should not be shown by default to "regular" users. At the same time, we don't want to end up in a situation where you have to maintain two version of your OMPL code.

**Comment by isucan** [comment]
I am with Mark on this one. My concern is that we will use use colors with any output handler, not just the default OMPL console one, if we manually specify colors. How strongly do you feel about this Dave? I would actually prefer leaving the color defines private as well (in the .cpp file)

**Comment by davetcoleman** [comment]
> Do you want to way in the output handler to force color, even if output is redirected to a file? In that case, the colors would still show up correctly if you look at the file in a terminal (maybe, I haven't tried).

I don't really think about redirection to a file - is that common? I guess that is how logging is done. I personally never do it so its behavior in files is not important to me.

> Would it be possible to limit your custom color output messages to use colors that aren't already in use by the standard OMPL log commands?

That makes sense to me, i.e. do not use Green, Yellow, or Red unless with OMPL_INFORM etc commands.

> Furthermore, would it be possible to limit these message to verbose mode (and have verbose=false by default)?

Sure, makes sense also. I could also just use a compiler directive to only enable them when in "developer mode".

>  if we manually specify colors.

You are saying we should not allow *any* colors to be used outside of the OMPL_*() commands?

**Comment by mamoll** [comment]
We could additional LogLevel values (e.g., LOG_DEVMSG1, LOG_DEVMSG2, ...), define OMPL_DEVMSG1, OMPL_DEVMSG2, ... macros analogous to OMPL_ERROR, and handle the colors in Console.cpp. The istty check would happen inside Console.cpp. Your code would never set any color codes.

**Comment by davetcoleman** [comment]
> define additional LogLevel values (e.g., LOG_DEVMSG1, LOG_DEVMSG2, ...), define OMPL_DEVMSG1, OMPL_DEVMSG2

I really like this idea, could we do this?

**Comment by mamoll** [comment]
Done in 1081ae6ac819ca75d95270e8d15127f0a66e31b7.

**Pull request closed without merging**
